core/urls.py
from django.urls import path
from . import views

app_name = 'core'

urlpatterns = [
    path('',views.ProductList.as_view(),name='product_list'),
    path('product/create/',views.ProductCreateView.as_view(),name='product_create'),
    path('product/<int:pk>/',views.ProductUpdateView.as_view(),name='product_update'),
    path('product/<int:pk>/delete',views.ProductDeleteView.as_view(),name='product_delete'),
    path('detail/<int:pk>/',views.product_detail,name='product_detail'),
    path('category/<category_slug>/',views.list_of_product_by_category,name='list_of_product_by_category'),
    path('checkout/',views.CheckoutView.as_view(),name='checkoutpage'),
    path('order-summary/',views.OrderSummaryView.as_view(),name='order-summary'),
    path('add-to-cart/<int:pk>/',views.add_to_cart,name='add-to-cart'),
    path('remove-from-cart/<int:pk>/',views.remove_from_cart,name='remove_from_cart'),
    path('remove-single-item-from-cart/<int:pk>/',views.remove_single_item_from_cart,name='remove-single-item-from-cart'),
    path('payment/<payment_option>/',views.PaymentView.as_view(),name='payment'),
    path('profile/',views.profile,name='profile'),
    path('account_update/',views.update_profile,name='account_update'),
    path('search/',views.SearchResultsView.as_view(),name='search_results'),
    path('comment/<int:pk>/delete/',views.comment_remove,name='comment_delete'),
    path('add-coupon/',views.AddCouponView.as_view(),name='add-coupon'),
]

eshop/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls.i18n import i18n_patterns

urlpatterns = [
]

urlpatterns += i18n_patterns(
    path('admin/', admin.site.urls),
    path('i18n/',include('django.conf.urls.i18n')),
    path('',include('core.urls',namespace='core')),
    path('accounts/', include('allauth.urls')),
    path('ratings/', include('star_ratings.urls', namespace='ratings',)),
    prefix_default_language=False,
)

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

templates/account_update.html
{% extends 'base.html' %}

{% load i18n %}

{% load crispy_forms_tags %}

{% block content %}
<div class="container mt-5 mb-5">
<h4>{% trans "Update your account" %}</h4>
<form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {{ user_form|crispy }}
        {{ profile_form|crispy }}
        <button class="btn btn-primary" type="submit">{% trans "Save changes" %}</button>
      </form>
</div>
{% endblock content %}

templates/base.html
{% load static i18n %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{% block title %}{% endblock title %}</title>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.11.2/css/all.css">
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/shop-homepage.css' %}" rel="stylesheet">
    <link href="{% static 'css/shop-item.css' %}" rel="stylesheet">
    <link href="{% static 'css/styles.css' %}" rel="stylesheet">    
    <link rel="stylesheet" href="{% static 'star-ratings/css/star-ratings.css' %}">
    {% block extra_head %}
    {% endblock extra_head %}
</head>
<body>

    {% include 'navbar.html' %}

    {% block content %}
    {% endblock content %}

    {% include 'footer.html' %}
        <script src="{% static 'js/jquery.min.js' %}"></script>
        <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
        <script src="{% static 'js/scripts.js' %}"></script>
        <script type="text/javascript" src="{% static 'star-ratings/js/dist/star-ratings.min.js' %}"></script>
</body>
</html>

templates/checkout-page.html
{% extends 'base.html' %}

{% load i18n %}

{% load static %}

{% load crispy_forms_tags %}

{% block content %}

  <!--Main layout-->
  <main>
    <div class="container wow fadeIn">

      <!-- Heading -->
      <h2 class="my-5 h2 text-center">{% trans "Checkout form" %}</h2>

      <!--Grid row-->
      <div class="row">

        <!--Grid column-->
        <div class="col-md-8 mb-4">

          <!--Card-->
          <div class="card">

            <!--Card content-->
            <form method="POST" class="card-body">
            {% csrf_token %}

             <h3>{% trans "Shipping address" %}</h3>

              <div class='hideable_shipping_form'>

                <div class="md-form mb-5">
                  <input type='text' placeholder='1234 Main St' id='shipping_address' name='shipping_address' class='form-control' />
                  <label for="shipping_address" class="">{% trans "Address" %}</label>
                </div>

                <div class="md-form mb-5">
                  <input type='text' placeholder='Apartment or suite' id='shipping_address2' name='shipping_address2' class='form-control' />
                  <label for="shipping_address2" class="">{% trans "Address2 (optional)" %}</label>
                </div>

                <div class="row">
                  <div class="col-lg-4 col-md-12 mb-4">
                    <label for="country">{% trans "Country" %}</label>
                    {{ form.shipping_country }}
                    <div class="invalid-feedback">
                      {% trans "Please select a valid country." %}
                    </div>
                  </div>
                  <div class="col-lg-4 col-md-6 mb-4">
                    <label for="shipping_zip">{% trans "Zip" %}</label>
                    <input type='text' placeholder='Zip code' id='shipping_zip' name='shipping_zip' class='form-control' />
                    <div class="invalid-feedback">
                      {% trans "Zip code required." %}
                    </div>
                  </div>
                </div>
                <div class="custom-control custom-checkbox">
                  <input type="checkbox" class="custom-control-input" name="set_default_shipping" id="set_default_shipping">
                  <label class="custom-control-label" for="set_default_shipping">{% trans "Save as default shipping address" %}</label>
                </div>
              </div>
              {% if default_shipping_address %}
              <div class="custom-control custom-checkbox">
                <input type="checkbox" class="custom-control-input" name="use_default_shipping" id="use_default_shipping">
                <label class="custom-control-label" for="use_default_shipping">{% trans "Use default shipping address: " %}{{ default_shipping_address.street_address|truncatechars:10 }}</label>
              </div>
              {% endif %}
              <hr>
                <h3>{% trans "Payment" %}
                    <option value=""></option></h3>
              <div class="d-block my-3">
                {% for value, name in form.fields.payment_option.choices %}
                <div class="custom-control custom-radio">
                  <input id="{{ name }}" name="payment_option" value="{{ value }}" type="radio" class="custom-control-input" required>
                  <label class="custom-control-label" for="{{ name }}">{{ name }}</label>
                </div>
                {% endfor %}
              </div>

              <hr class="mb-4">
              <button class="btn btn-primary btn-lg btn-block" type="submit">{% trans "Continue to checkout" %}</button>

            </form>

          </div>
          <!--/.Card-->

        </div>
        <!--Grid column-->

        <!--Grid column-->
        <div class="col-md-4 mb-4">
        {% include 'order_snippet.html' %}

          <!-- Cart -->

        </div>
        <!--Grid column-->

      </div>
      <!--Grid row-->

    </div>
  </main>
  <!--Main layout-->

{% endblock %}

{% block extra_scripts %}
<script>
var hideable_shipping_form = $('.hideable_shipping_form');
var use_default_shipping = document.querySelector("input[name=use_default_shipping]");
use_default_shipping.addEventListener('change', function() {
  if (this.checked) {
    hideable_shipping_form.hide();
  } else {
    hideable_shipping_form.show();
  }
})
</script>
{% endblock extra_scripts %}

templates/footer.html
<footer class="py-5 bg-dark">
        <div class="container">
          <p class="m-0 text-center text-white">Copyright &copy; Your Website 2019</p>
        </div>
        <!-- /.container -->
      </footer>

templates/navbar.html
{% load i18n %}

<nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
        <div class="container">
          <a class="navbar-brand" href="{% url 'core:product_list' %}">EShop</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav ml-auto">
              {% if user.is_authenticated %}
              <li class="nav-item">
                  <a class="nav-link" href="{% url 'core:profile' %}"><i class="fas fa-user"></i> {% trans "Username:" %} {{ user.username }}
                  </a>
                </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'account_logout' %}">{% trans "Logout" %}
                </a>
              </li>
              <li class="nav-item">
                  <a class="nav-link" href="{% url 'core:order-summary' %}"><i class="fas fa-shopping-cart"></i> {% trans "Cart" %}
                  </a>
                </li>
              {% else %}
              <li class="nav-item">
                  <a class="nav-link" href="{% url 'account_login' %}">{% trans "Login" %}
                  </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'account_signup' %}">{% trans "Sign Up" %}
                    </a>
                  </li>
              {% endif %}
              <form class="form-inline my-2 my-lg-0" method="get" action="{% url 'core:search_results' %}">
                  <input name='title' class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
                  <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
                </form>
                <li class="dropdown ml-3" id="language-switcher">
                    <form action="{% url 'set_language' %}" method="post">
                        {% csrf_token %}
                        <input name="next" type="hidden" value="{{ redirect_to }}" />
                        <select class="selectpicker" name="{% trans 'language' %}" style="width: auto;" onchange="this.form.submit()">
                          {% get_current_language as LANGUAGE_CODE %}
                          {% get_available_languages as LANGUAGES %}
                          {% get_language_info_list for LANGUAGES as languages %}
                          {% for language in languages %}
                              <option
                                value="{{ language.code }}"
                                {% if language.code == LANGUAGE_CODE %} selected="selected"{% endif %}
                                data-content='<img src="/static/img/flags/{{ language.code }}.png"></span>
                                <span style="display:inline-block; width:100px; padding-left: 10px; text-shadow:none">
                                  {{ language.name_local }}
                                  <!-- span style="color:#999;">&nbsp;[{{ language.code }}]</span -->
                                </span>'>
                                {{ language.code }}
                              </option>
            
                          {% endfor %}
                        </select>
                    </form>
                </li>
            </ul>
          </div>
        </div>
      </nav>

templates/order_snippet.html
<div class="col-md-12 mb-4 mt-3">

    <!-- Heading -->
    <h4 class="d-flex justify-content-between align-items-center mb-3">
      <span class="text-muted">Your cart</span>
      <span class="badge badge-secondary badge-pill">{{ order.items.count }}</span>
    </h4>

    <!-- Cart -->
    <ul class="list-group mb-3 z-depth-1">
      {% for order_item in order.items.all %}
      <li class="list-group-item d-flex justify-content-between lh-condensed">
        <div>
          <h6 class="my-0">{{ order_item.quantity }} x {{ order_item.item.title }}</h6>
          <small class="text-muted">{{ order_item.item.description }}</small>
        </div>
        <span class="text-muted">${{ order_item.get_final_price }}</span>
      </li>
      {% endfor %}
      {% if order.coupon %}
      <li class="list-group-item d-flex justify-content-between bg-light">
        <div class="text-success">
          <h6 class="my-0">Promo code</h6>
          <small>{{ order.coupon.code }}</small>
        </div>
        <span class="text-success">-${{ order.coupon.amount }}</span>
      </li>
      {% endif %}
      <li class="list-group-item d-flex justify-content-between">
        <span>Total (USD)</span>
        <strong>${{ order.get_total }}</strong>
      </li>
    </ul>
    <!-- Cart -->

    {% if DISPLAY_COUPON_FORM %}
    <form method="POST" action="{% url 'core:add-coupon' %}" class="card p-2">
      {% csrf_token %}
      <div class="input-group">
        {{ couponform.code }}
        <div class="input-group-append">
          <button type="submit" class="btn btn-secondary">Redeem</button>
        </div>
      </div>
    </form>
    {% endif %}
</div>

templates/order_summary.html
{% extends 'base.html' %}

{% load i18n %}

{% block content %}

<main>
    <div class="container mt-5">
        <div class="table-responsive text-nowrap">
        <h2>{% trans "Order Summary" %}</h2>
  <table class="table">
    <thead>
      <tr>
        <th scope="col">#</th>
        <th scope="col">{% trans "Item title" %}</th>
        <th scope="col">{% trans "Price" %}</th>
        <th scope="col">{% trans "Quantity" %}</th>
        <th scope="col">{% trans "Total Item Price" %}</th>
      </tr>
    </thead>
    <tbody>
      {% for order_item in object.items.all %}
      <tr>
        <th scope="row">{{ forloop.counter }}</th>
        <td>{{ order_item.item.title }}</td>
        <td>{{ order_item.item.price }}</td>
        <td>
          <a href="{% url 'core:remove-single-item-from-cart' order_item.item.pk %}"><i class="fas fa-minus mr-2"></i></a>
          {{ order_item.quantity }}
          <a href="{% url 'core:add-to-cart' order_item.item.pk %}"><i class="fas fa-plus ml-2"></i></td></a>
        <td>
            {% if order_item.item.discount_price %}
            {{ order_item.get_total_discount_item_price }}
           <span class="badge badge-primary">Saving ${{ order_item.get_amount_saved }}</span>
         {% else %}
            {{ order_item.get_total_item_price }}
         {% endif %}
           <a style='color:red;' href="{% url 'core:remove_from_cart' order_item.item.pk %}">
             <i class="fas fa-trash float-right"></i>
           </a>
        </td>
      </tr>
      {% empty %}
      <tr>
        <td colspan="5">{% trans "Your cart is empty" %}</td>
      </tr>
       <tr>
        <td colspan="5">
          <a class="btn btn-primary float-right" href="{% url 'core:product_list' %}">{% trans "Continue shopping" %}</a>
        </td>
      </tr>
      {% endfor %}
      {% if object.coupon %}
      {% endif %}
      <tr>
        <td colspan="4"><b>Coupon</b></td>
        <td><b>-${{ object.coupon.amount }}</b></td>
      </tr>
      {% if object.get_total %}
      <tr>
        <td colspan="4"><b>{% trans "Order Total" %}</b></td>
        <td><b>${{ object.get_total }}</b></td>
      </tr>
      <tr>
        <td colspan="5">
          <a class="btn btn-warning float-right ml-2" href="{% url 'core:checkoutpage' %}">{% trans "Proceed to checkout" %}</a>
          <a class="btn btn-primary float-right" href="{% url 'core:product_list' %}">{% trans "Continue shopping" %}</a>
        </td>
      </tr>
      {% endif %}
    </tbody>
  </table>

</div>
    </div>
</main>

{% endblock %}

templates/product_create.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block content %}
<main class="mt-5">
<div class="container">
<section class="mb-4">
<div class="row wow fadeIn">
<div class="col-6 offset-3">
<h2 class="mb-3">Add a new product</h2>
  <div class="row">
    <div class="col-md-6 col-sm-8 col-12">
      <form method="post" novalidate enctype="multipart/form-data">
        {% csrf_token %}
        {{ form|crispy }}
        <button type="submit" class="btn btn-success">Save</button>
      </form>
    </div>
  </div>
</div>
</div>
</section>
</div>
</main>
{% endblock content %}

templates/product_delete.html
{% extends 'base.html' %}

{% block content %}
<section class="mt-3 mb-3">
<form method="post">
{% csrf_token %}
<button type="submit" class="btn btn-danger btn-lg">{% trans "Yes, I'm sure" %}</button>
</form>
</section>
{% endblock %}

templates/product_detail.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% load humanize %}

{% block content %}
      <!-- Page Content -->
      <div class="container">
    
        <div class="row">
    
          
          <!-- /.col-lg-3 -->
    
          <div class="col-lg-9">
    
            <div class="card mt-4">
              <img class="card-img-top img-fluid" style="height: 350px;width: 350px;" src="{{ item.image.url }}" alt="">
              <div class="card-body">
                <p class="float-right">Category: <i
                    {% if item.category.name == 'Phones' %} 
                    class="fas fa-mobile"
                    {% elif item.category.name == 'Clothes' %}
                    class="fas fa-tshirt"
                    {% elif item.category.name == 'Albums' %}
                    class="fas fa-music"
                    {% elif item.category.name == 'Cameras' %}
                    class="fas fa-camera"
                    {% elif item.category.name == 'Tablets' %}
                    class="fas fa-tablet"
                    {% elif item.category.name == 'Books' %}
                    class="fas fa-book"
                    {% endif %}
                ></i> {{ item.category }}</p>
                <h3 class="card-title">Product name: {{ item.title }}</h3>
                <h4>Price: {{ item.price }}</h4>
                <p class="card-text">Description: {{ item.description }}</p>
                <span class="text-warning">&#9733; &#9733; &#9733; &#9733; &#9734;</span>
                4.0 stars
              </div>
            </div>
            <!-- /.card -->
    
            <div class="card card-outline-secondary my-4">
              <div class="card-header">
                Product Reviews
                {{ comments.count }}
              </div>
              {% for comment in comments %}
              <div class="card-body">
                <p>{{ comment.body }}</p>
                <a class="float-right btn btn-outline-danger btn-sm" href="{% url 'core:comment_delete' pk=comment.pk %}"><span class="fas fa-trash"></span> Delete</a><br>
                <small class="text-muted">Posted by {{ user.username }} on {{ comment.created_on|naturaltime }}</small>
                <hr>
              </div>
              {% endfor %}
            </div>
            <!-- /.card -->
            <div class="card my-4" style="width: 30rem;">
                <h5 class="card-header ml-0">Leave a review <small> as {{ user.username }}</small></h5>
                <div class="card-body">
                  <form method="POST">
                    <div class="form-group">
                        {{ comment_form|crispy }}
                        {% csrf_token %}
                        <input type="submit" value="Post Comment" class="btn btn-info">
                    </div>
                  </form>
                </div>
              </div>
    
          </div>
          <!-- /.col-lg-9 -->
    
        </div>
    
      </div>
      <!-- /.container -->
{% endblock content %}

templates/product_list.html
{% extends 'base.html' %}

{% load i18n %}

{% load humanize %}

{% block content %}
      <!-- Page Content -->
      <div class="container">
        <div class="row">
          <div class="col-lg-3">
            <h2 class="my-4">{% trans "Shop by category" %}</h2>
            <div class="btn-group">
                <button type="button" class="btn btn-outline-primary dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    {% trans "All categories" %}
                </button>
                <div class="dropdown-menu">
                    <a href="category/P/" class="dropdown-item">{% trans "Phones" %}</a>
                    <div class="dropdown-divider"></div>
                    <a href="category/C/" class="dropdown-item">{% trans "Clothes" %}</a>
                    <div class="dropdown-divider"></div>
                    <a href="category/A/" class="dropdown-item">{% trans "Albums" %}</a>
                    <div class="dropdown-divider"></div>
                    <a href="category/B/" class="dropdown-item">{% trans "Books" %}</a>
                    <div class="dropdown-divider"></div>
                    <a href="category/CA/" class="dropdown-item">{% trans "Cameras" %}</a>
                    <div class="dropdown-divider"></div>
                    <a href="category/TA/" class="dropdown-item">{% trans "Tablets" %}</a>
                </div>
              </div>
          </div>
          <!-- /.col-lg-3 -->
          <div class="col-lg-9">
            <div id="carouselExampleIndicators" class="carousel slide my-4" data-ride="carousel">
              <div class="carousel-inner" role="listbox">
                {% for slide in slides %}
                <div style="background-color:darkgray" class="carousel-item {% cycle 'active' '' '' %}">
                  <img class="d-block img-fluid" style="height:350px;width:350px; margin-left:78px;" src="{{slide.image.url}}" alt="First slide">
                <div class="carousel-caption text-left" style="margin-bottom:150px;">
                    <h3 style="color:black;margin-left:400px;">{{slide.title}}</h3>
                    <p style="color:black;margin-left:400px;">{{slide.text}}</p>
                </div>
                </div>
                {% endfor %}
              </div>
              <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
                <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                <span class="sr-only">{% trans "Previous" %}</span>
              </a>
              <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
                <span class="carousel-control-next-icon" aria-hidden="true"></span>
                <span class="sr-only">{% trans "Next" %}</span>
              </a>
            </div>
            <div class="row">
                {% for item in object_list %}
              <div class="col-lg-4 col-md-6 mb-4">
                <div class="card h-100">
                  <img style="height:150px;width:150px;" class="card-img-top ml-5" src="{{ item.image.url }}" alt="">
                  <div class="card-body">
                    <h4 class="card-title">
                      <a href="{{ item.get_absolute_url }}">{{ item.title }}</a>
                    </h4>
                    {% if item.discount_price %}
                    <span class="badge badge-pill badge-success">Discount</span><br>
                    <span class="oldprice">
                        <b>${{ item.price }}</b>
                      </span>
                      <span class="newprice ml-2">
                        <b>${{ item.discount_price }}</b>
                      </span>
                    {% else %}
                    <b><p>${{ item.price }}</p></b>
                    {% endif %}
                    <p class="card-text">{{ item.description }}</p>
                  </div>
                  <div class="card-footer">
                      {% if request.user == item.user %}
                      <a class="btn btn-outline-primary btn-sm mb-2" href="{% url 'core:product_update' pk=item.pk %}"><span class="fas fa-edit"></span> {% trans "Update" %}</a>
                      <a class="float-right btn btn-outline-danger btn-sm" href="{% url 'core:product_delete' pk=item.pk %}"><span class="fas fa-trash"></span> {% trans "Delete" %}</a><br>
                      {% endif %}
                      <a class="btn btn-outline-primary btn-sm" href="{% url 'core:product_detail' pk=item.pk %}"><span class="fas fa-eye"></span> {% trans "VIEW PRODUCT" %}</a>
                      <a class="float-right btn btn-outline-primary btn-sm" href="{% url 'core:add-to-cart' pk=item.pk %}"><span class="fas fa-cart-plus"></span></a><br>
                    <small class="text-muted">&#9733; &#9733; &#9733; &#9733; &#9734;</small>
                    <p class="card-text">{% trans "Category:" %} <i
                      {% if item.category.name == 'Phones' %} 
                      class="fas fa-mobile"
                      {% elif item.category.name == 'Clothes' %}
                      class="fas fa-tshirt"
                      {% elif item.category.name == 'Albums' %}
                      class="fas fa-music"
                      {% elif item.category.name == 'Cameras' %}
                      class="fas fa-camera"
                      {% elif item.category.name == 'Tablets' %}
                      class="fas fa-tablet"
                      {% elif item.category.name == 'Books' %}
                      class="fas fa-book"
                      {% endif %}
                  ></i> {{ item.category }}</p>
                  <p class="float-right">{% trans "Views:" %} {{ item.views }}</p>
                  <p class="card-text">{{ item.published_on|naturaltime }}</p>
                  </div>
                </div>
              </div>
              {% endfor %}
            </div>
            <!-- /.row -->
            {% if is_paginated %}
           
        <ul class="pagination justify-content-center mb-4">
            {% if page_obj.has_previous %}
            <li class="page-item">
              <a class="page-link" href="?page={{ page_obj.previous_page_number }}">&larr; Older</a>
            </li>
            {% else %}
            <li class="page-item disabled">
                <a class="page-link" href="#">&larr; Older</a>
              </li>
            {% endif %}
  
            {% for i in paginator.page_range %}
      {% if page_obj.number == i %}
        <li class="page-item active"><span class="page-link">{{ i }} <span class="sr-only">(current)</span></span></li>
      {% else %}
        <li class="page-item"><a class="page-link" href="?page={{ i }}">{{ i }}</a></li>
      {% endif %}
    {% endfor %}

            {% if page_obj.has_next %}
            <li class="page-item">
              <a class="page-link" href="?page={{ page_obj.next_page_number }}">Newer &rarr;</a>
            </li>
            {% else %}
            <li class="page-item disabled">
                <a class="page-link" href="#">Newer &rarr;</a>
              </li>
            {% endif %}
          </ul>
              {% endif %}
          </div>
          <!-- /.col-lg-9 -->
        </div>
        <!-- /.row -->
      </div>
      <!-- /.container -->
{% endblock content %}

templates/product_update.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block content %}
<main class="mt-5">
<div class="container">
<section class="mb-4">
<div class="row wow fadeIn">
<div class="col-6 offset-3">
<h2 class="mb-3">
    {{ item.title }}
      </h2>
      <div class="row mb-3">
        <div class="col-md-6 col-sm-8 col-12">
          <form method="post" novalidate enctype="multipart/form-data">
            {% csrf_token %}
            {{ form|crispy }}
            <button type="submit" class="btn btn-success">{% trans "Save changes" %}</button>
          </form>
        </div>
      </div>
</div>
</div>
</section>
</div>
</main>
{% endblock %}

templates/request_refund.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block content %}

<main>
    <div class="container">
        <h2>Request Refund</h2>
        <form method="POST">
            {% csrf_token %}
            {{ form|crispy }}
            <button type="submit" class="btn btn-primary">Submit</button>
        </form>
    </div>
</main>

{% endblock %}